### ISSUE TITLE
Update read tracker count (final graphs)

### ISSUE THREAD

**Issue by corinnewalsh** [fiererlab/dada2_fiererlab#19] opened 2022-02-07 15:18 UTC
The final read tracker graphs do not work for calculating reads through the "pooled" or "psuedo pooled" version of the pipeline. Update / add new calculations to count reads throughout the entire process.

**Comment by cliffbueno** [comment] 2024-11-15 20:56
Duplicate of #15 

This will be implemented in version 2.0.0.

**Closed as completed by cliffbueno** 2024-11-15 20:56 UTC
Labels: duplicate, enhancement
